#! /bin/sh
# /etc/init.d/dride-ws

case "$1" in
  start)
    echo "Starting dride-ws"
    # run node-express server
    sudo node /home/Cardigan/dride-ws/server/app.js &
    ;;
  stop)
    echo "Stopping dride-ws"
    # kill application you want to stop
    killall node
    ;;
  *)
    echo "Usage: /etc/init.d/dride-ws{start|stop}"
    exit 1
    ;;
esac

exit 0